config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :reports do
    get :download, on: :member
    get :carton, on: :member
    get :picklist, on: :member
    post :upload_list_items, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  has_one_attached :list_items
end

app/models/report.rb
class Report < ApplicationRecord

  before_save :set_uuid

  has_one_attached :original
  has_one_attached :promotion
  has_one_attached :report_detail

  def set_uuid
    random_uuid = SecureRandom.hex(8)
    if Report.exists?(uuid: random_uuid)
      set_uuid
    else
      self.uuid = random_uuid
    end
  end

  def original_sheet
    original.open { |file| Roo::Spreadsheet.open(file) }
  end

  def promotion_sheet
    promotion.open { |file| Roo::Spreadsheet.open(file) }
  end

  def list_items_sheet
    Page.last.list_items.open { |file| Roo::Spreadsheet.open(file) }
  end

  def perfrom
    weight_items = {}
    list_items = list_items_sheet.parse

    promotion_sheet.each(dh: 'ĐƠN HÀNG', item_id: 'Item#', sll: 'Qty') do |promo_hash|
      list_items.each do |row|
        if row.include?(promo_hash[:item_id])
          item_wei = row[-1].to_f * promo_hash[:sll].to_i
          weight_items[promo_hash[:dh]] = weight_items.key?(promo_hash[:dh]) ? weight_items[promo_hash[:dh]] + item_wei : item_wei
        end
      end
    end

    weight_items
  end

  def get_items_by(dh)
    items = []
    result = []
    promotion_sheet.each(dh: 'ĐƠN HÀNG', item_id: 'Item#', sll: 'Qty') do |p_hash|
      (p_hash[:dh] == dh) ? items << [p_hash[:item_id], p_hash[:sll]] : nil
    end

    data = list_items_sheet.parse

    items.each do |id|
      data.select do |row|
        if row.include?(id[0])
          row.push(id[1])
          result << row
        end
      end
    end

    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    answer = ((rand(10)%2) == 1) ? “Yes” : “No”
    render json: {answer: answer}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.fetch(:page, {})
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @new_report = Report.new
    @new_page = Page.new
    @reports = Report.all
    @page = Page.last
  end

  def show
    @report = Report.find(params[:id])
  end

  def carton
    @report = Report.find(params[:id])
    @weight_items = @report.perfrom
    data_original = @report.original_sheet.parse
    @carton = data_original.select {|row| row.include?(params[:dh])}[0]
    @items = @report.get_items_by(params[:dh])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "carton", encoding: 'UTF-8'
      end
    end
  end

  def create
    @new_report = Report.new(report_params)
    if @new_report.save
      redirect_to reports_path
    end
  end

  def upload_list_items
    @new_page = Page.new(list_items_params)
    if @new_page.save
      redirect_to reports_path
    end
  end

  def download
    @report = Report.find(params[:id])
    respond_to do |format|
      format.xlsx
    end
  end

  def destroy
    @report = Report.find(params[:id])
    if @report.destroy
      redirect_to reports_path
    end
  end

  def picklist
    @report = Report.find(params[:id])
    @data_original = @report.original_sheet.parse
    @data_promotion = @report.promotion_sheet
    @data_list_items = @report.list_items_sheet

    respond_to do |format|
      format.pdf do
        render pdf: "picklist", encoding: 'UTF-8', page_size: 'A4'
      end
    end
  end

  private

  def report_params
    params.require(:report).permit(:original, :promotion)
  end

  def list_items_params
    params.require(:page).permit(:list_items)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper

  def get_items_by(dh, promotion_sheet, list_items_sheet)
    items = []
    result = []
    promotion_sheet.each(dh: 'ĐƠN HÀNG', item_id: 'Item#', sll: 'Qty') do |p_hash|
      (p_hash[:dh] == dh) ? items << [p_hash[:item_id], p_hash[:sll]] : nil
    end

    data = list_items_sheet.parse

    items.each do |id|
      data.select do |row|
        if row.include?(id[0])
          row.push(id[1])
          result << row
        end
      end
    end

    result
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>V3Robot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %> -->

<%= javascript_pack_tag "robot" %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/reports/carton.html.erb
<table class="table">
  <tr colspan="3">
    <td>Nhãn Thùng / Phiếu Soạn Hàng</td>
  </tr>
  <tr>
    <td>Tỉnh</td>
    <td><%=@carton[2]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Số Đơn Hàng</td>
    <td><%=@carton[0]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Trọng Lượng</td>
    <td><%=@weight_items[@carton[0]]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Người Nhận 1</td>
    <td><%=@carton[4]%></td>
    <td></td>
  </tr>
  <tr>
    <td>SDT</td>
    <td><%=@carton[6]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Người Nhận 2</td>
    <td><%=@carton[8]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Sô Lượng Lì XÌ</td>
    <td><%=@items.count %></td>
    <td></td>
  </tr>
  <tr>
    <td>Mã Hàng</td>
    <td>Vị Trí</td>
    <td>Số Lượng</td>
  </tr>
  <%@items.each do |item|%>
  <tr>
    <td><%=item[0]%></td>
    <td><%=item[2]%></td>
    <td><%=item[4]%></td>
  </tr>
  <%end%>
  <tr>
    <td>Vendor</td>
    <td><%=@carton[3]%></td>
    <td></td>
  </tr>
</table>

app/views/reports/carton.pdf.erb
<table class="table">
  <tr colspan="3">
    <td>Nhãn Thùng / Phiếu Soạn Hàng</td>
  </tr>
  <tr>
    <td>Tỉnh</td>
    <td><%=@carton[2]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Số Đơn Hàng</td>
    <td><%=@carton[0]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Trọng Lượng</td>
    <td><%=@weight_items[@carton[0]]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Người Nhận 1</td>
    <td><%=@carton[4]%></td>
    <td></td>
  </tr>
  <tr>
    <td>SDT</td>
    <td><%=@carton[6]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Người Nhận 2</td>
    <td><%=@carton[8]%></td>
    <td></td>
  </tr>
  <tr>
    <td>Sô Lượng Lì XÌ</td>
    <td><%=@items.count %></td>
    <td></td>
  </tr>
  <tr>
    <td>Mã Hàng</td>
    <td>Vị Trí</td>
    <td>Tên Hàng</td>
  </tr>
  <%@items.each do |item|%>
  <tr>
    <td><%=item[0]%></td>
    <td><%=item[2]%></td>
    <td><%=item[3]%></td>
  </tr>
  <%end%>
  <tr>
    <td>Vendor</td>
    <td><%=@carton[3]%></td>
    <td></td>
  </tr>
</table>

app/views/reports/index.html.erb
<h1 class="text-center">This is reportsSelect page</h1 File>


<div class="form-content row">
  <div class="form-process col">
    <%= form_for @new_report do |f| %>
      <label class="">Select Original File :</label>
      <br>
      <%= f.file_field :original %>
      <br class="mb-3">
      <label class="">Select Promotion File :</label>
      <br>
      <%= f.file_field :promotion %>
      <br class="mb-3">
      <%= f.submit 'Proress', class: 'mb-5'%>
    <%end%>
  </div>
  <div class="form-list-items col">
    <p>
      <span>Current List Items : </span> <%= @page&.list_items&.name%>
      <br>
      <span>Upload At : </span> <%= @page&.created_at%>
    </p>
    <%= form_for @new_page, url: upload_list_items_reports_path do |f| %>
      <label class="">Select List Items File :</label>
      <br>
      <%= f.file_field :list_items %>
      <br class="mb-3">
      <%= f.submit 'Upload List Items', class: 'mb-5'%>
    <%end%>
  </div>
</div>



<table class="table table-striped">
  <thead>
    <tr>
      <td>ID</td>
      <td>Created At</td>
      <td>Original File name</td>
      <td>Promotion File name</td>
      <td>List items File name</td>
      <td>Action</td>
    </tr>
  </thead>
  <tbody>
    <%@reports.each do |report|%>
      <tr>
        <td><%=report.id%></td>
        <td><%=report.created_at%></td>
        <td><%=report.original&.name%></td>
        <td><%=report.promotion&.name%></td>
        <td><%=@page&.list_items&.name%></td>
        <td>
          <%= link_to 'report detail', report_path(report), target: '_blank'%>&nbsp;|&nbsp;
          <%= link_to 'delete', report_path(report), method: :delete, data: { confirm: "Are you sure?" }%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/reports/picklist.pdf.erb
<%@data_original.sort! {|a,b| a[0] <=> b[0]}%>
<%@data_original.each do |data|%>
  <h1 style="text-align: center;">Phiếu Soạn Hàng</h1>
  <h3>Vendor:  <%= data[3]%></h3>
  <h3>Số Đơn Hàng:  <%= data[0]%></h3>

  <table class="table">
    <thead>
      <tr>
        <td width="15%">Mã Hàng</td>
        <td width="10%">Số Lượng </td>
        <td width="10%" >Vị Trí</td>
        <td>Tến Hàng</td>
      </tr>
    </thead>
    <tbody>
      <%get_items_by(data[0], @data_promotion, @data_list_items).each do |item|%>
        <tr>
          <td style="text-align: center;"><%=item[0]%></td>
          <td style="text-align: center;"><%=item[4]%></td>
          <td style="text-align: center;"><%=item[2]%></td>
          <td><%=item[1]%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <div class="page-break"></div>
<%end%>

<style>
  table tr td {
    border: 1px solid;
  }
  .page-break { display:block; clear:both; page-break-after:always; }
</style>

app/views/reports/show.html.erb
<h1 class="text-center mb-5">This is reportsSelect page</h1 File>



<%= link_to 'download bản kê', "/reports/#{@report.id}/download.xlsx", class: 'btn btn-warning mb-5'%>
<%= link_to 'picklist', "/reports/#{@report.id}/picklist.pdf", target: '_blank', class: 'btn btn-success mb-5'%>

<% weight_col = @report.perfrom %>
<% data = @report.original_sheet.parse %>

<table class="table table-striped">
  <thead>
    <tr>
      <% @report.original_sheet.row(1).insert(1, "Trọng Lượng").each do |title| %>
        <td><%= title%></td>
      <%end%>
      <td>Action</td>
    </tr>
  </thead>
  <tbody>
    <%data.each do |row|%>
      <tr>
        <td><%=row[0]%></td>
        <td><%= weight_col[row[0]]%></td>
        <td><%=row[1]%></td>
        <td><%=row[2]%></td>
        <td><%=row[3]%></td>
        <td><%=row[4]%></td>
        <td><%=row[5]%></td>
        <td><%=row[6]%></td>
        <td><%=row[7]%></td>
        <td><%=row[8]%></td>
        <td>
          <%= link_to 'Carton detail', carton_report_path(dh: row[0]), target: '_blank'%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>